// Code generated by "stringer -type=Level"; DO NOT EDIT

package Logger

import "fmt"

const _Level_name = "NoneEmergencyAlertCriticalErrorWarningNoticeInfoDebug"

var _Level_index = [...]uint8{0, 4, 13, 18, 26, 31, 38, 44, 48, 53}

func (i Level) String() string {
	i -= -1
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return fmt.Sprintf("Level(%d)", i+-1)
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
