// Code generated by "stringer -type=Format"; DO NOT EDIT

package Parser

import "fmt"

const _Format_name = "DefaultXMLDefaultJSONDefaultYAML"

var _Format_index = [...]uint8{0, 10, 21, 32}

func (i Format) String() string {
	i -= 2
	if i < 0 || i >= Format(len(_Format_index)-1) {
		return fmt.Sprintf("Format(%d)", i+2)
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
