// Code generated by "stringer -type=ErrorType"; DO NOT EDIT

package customErrors

import "fmt"

const _ErrorType_name = "BasicErrorInvalidOperationInvalidArgumentAccessViolationNonsupported"

var _ErrorType_index = [...]uint8{0, 10, 26, 41, 56, 68}

func (i ErrorType) String() string {
	if i < 0 || i >= ErrorType(len(_ErrorType_index)-1) {
		return fmt.Sprintf("ErrorType(%d)", i)
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
