// Code generated by "stringer -type=SupportedCodec"; DO NOT EDIT

package Parcer

import "fmt"

const _SupportedCodec_name = "DefaultXMLDefaultJSONDefaultYAML"

var _SupportedCodec_index = [...]uint8{0, 10, 21, 32}

func (i SupportedCodec) String() string {
	if i < 0 || i >= SupportedCodec(len(_SupportedCodec_index)-1) {
		return fmt.Sprintf("SupportedCodec(%d)", i)
	}
	return _SupportedCodec_name[_SupportedCodec_index[i]:_SupportedCodec_index[i+1]]
}
